name: ansible-lab

services:
  controller:
    container_name: controller
    image: riveroverflow/ansible-lab:1.1
    entrypoint: /bin/bash
    command: 
      - -c
      - sleep infinity
    networks:
      - ansible
    volumes:
      - ./playbooks:/root/playbooks
      - ./controller-ssh:/root/.ssh
      - ./scripts:/root/scripts
    working_dir: /root/playbooks

  server-1:
    container_name: server-1
    image: riveroverflow/ansible-lab:1.1
    networks:
      - ansible

  server-2:
    container_name: server-2
    image: riveroverflow/ansible-lab:1.1
    networks:
      - ansible

  server-3:
    container_name: server-3
    image: riveroverflow/ansible-lab:1.1
    networks:
      - ansible
  
networks:
  ansible:
    name: "ansible_network"
